### ISSUE TITLE
process exited with code 25

### ISSUE THREAD

**Issue by Lito124908371204938** [agnat/node_wake_on_lan#12]
trying to install that thing:

$ ./iobroker url "https://github.com/agnat/node_wake_on_lan" --debug
install https://github.com/agnat/node_wake_on_lan/tarball/dd6404623ccf4bc55b0ba8788ba38312b55435a1
NPM version: 6.14.8npm install https://github.com/agnat/node_wake_on_lan/tarball/dd6404623ccf4bc55b0ba8788ba38312b55435a1 --loglevel error --prefix "/opt/iobroker" (System call)
> sharp@0.25.2 install /opt/iobroker/node_modules/sharp> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
ERR!
 
sharp Use with glibc 2.24 requires manual installation of libvips >= 8.9.1
info
 sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
make: Entering directory '/opt/iobroker/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:23:22: fatal error: vips/vips8: No such file or directory #include <vips/vips8>                      ^compilation terminated.
sharp.target.mk:130: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: Leaving directory '/opt/iobroker/node_modules/sharp/build'make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! 
stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)gyp ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)gyp 
ERR! System Linux 4.14.79-v7+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/sharpgyp ERR! node -v v10.23.0gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
+ wake_on_lan@1.0.0updated 1 package in 66.919s
61 packages are looking for funding  run `npm fund` for details
ERROR: host.raspberrypi Cannot install https://github.com/agnat/node_wake_on_lan/tarball/dd6404623ccf4bc55b0ba8788ba38312b55435a1: 0
ERROR: process exited with code 25

**Comment by agnat** [comment]
I'm sorry, but I don't support `iobroker`. Installing with `npm` works fine. Note, the error has nothing to do with `wake_on_lan`. It tries to install `sharp` and fails. No idea why.

I'm going to close this.
