### ISSUE TITLE
Don't send wol after 1 minute when I send device power off command.

### ISSUE THREAD

**Issue by MasterBS** [agnat/node_wake_on_lan#5]
Server and Client device bind local network.

After I sent a power-off instruction of the client device, I have succeeded when the WOL transmitted within 1 minute to the client device.

WOL don't send to the client when the client device power off more than a minute.

So I need your advice.

var wol = require('wake_on_lan');
var opts = {
	address : ipAddress
};
wol.wake(macAddr, opts, function(error){
	if(error){
		if(typeof fnCallback == "function"){
			fnCallback(false);
		}
	}else{
		if(typeof fnCallback =="function"){
			fnCallback(true);
	}
}

**Comment by agnat** [comment]
Ok, just real quick:

Don't use the ip address of the device. Either use the broadcast address of the network segment or no ip address at all (global broadcast). What happens is that your switch "forgets" which port this ip address was on... apparently after a minute. If you want to learn more read about "ARP tables".

**Comment by MasterBS** [comment]
I understand your comment.

I will change to test by sending WOL that I get a broadcast address of the network segment or global broadcast.

Thank you.
