### ISSUE TITLE
npm install wake_on_lan --save Error I am getting

### ISSUE THREAD

**Issue by StarfighterJ** [agnat/node_wake_on_lan#9]
Reason I ask was seeing 2-3 days old, but this is what I get doing npm install wake_on_lan --save.
Also not sure if this is part of it but the .gitignore  file did not down load. I am trying to get a good wake on lan program to turn on my LGTV.
C:\Users\TEST\Downloads\node_wake_on_lan-master (1)\node_wake_on_lan-master>npm install wake_on_lan --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "wake_on_lan" under a package
npm ERR! also called "wake_on_lan". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TEST\AppData\Roaming\npm-cache\_logs\2018-05-23T18_12_55_122Z-debug.log

**Comment by agnat** [comment]
> [...] but this is what I get doing npm install wake_on_lan --save.

Please read the error message before opening an issue:

````
npm ERR! Refusing to install package with name "wake_on_lan" under a package
npm ERR! also called "wake_on_lan". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR! https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm
````

Also, read a tutorial or beginner's guide to npm.

> [...] the .gitignore file did not down load

Believe me, it's there: See [hidden files](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory)

Hope this helps.
